<?php
session_start();
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
	<title>Цифровая образовательная среда Орловской области</title>
</head>
<body>

	<form action="index.phtml" method="post" style="width: 30%;">
        <a href="/" style="margin: 1%"><i class="fas fa-arrow-left"></i></a>
        <div class="input-group" >
        <span class="input-group-text">Логин: </span>
        <input type="text" class="form-control" name="login"
    	value="<?php echo (isset($_POST["login"])) ? $_POST["login"] : null; // Заполняем поле по умолчанию ?>" />
        </div>
        <div class="input-group" >
        <span class="input-group-text">Пароль: </span>
        <input type="password" class="form-control" name="password" value="" />
        </div>
        <div class="btn-group" role="group">
            <button type="submit" class="btn btn-secondary" style="margin: 1%">Войти</button>
        </div>
	</form>
</body>
</html>

