<footer>
    <div class="container row">
        <div class="footer_contacts">
            <p class="title">Департамент образования Орловской области</p>
            <li class="adr"><i class="fas fa-map-marker-alt"></i> 302021, г. Орел, Ленина пл., д. 1.</li>
            <li class="mail"><i class="far fa-envelope"></i> E-mail: <a href="mailto:pr_obraz@adm.orel.ru">pr_obraz@adm.orel.ru</a></li>
            <li class="tel"><i class="fas fa-phone"></i> </i> <a href="tel:+74862598290">+7 (4862) 59-82-90</a></li>
            <li class="web"><i class="fas fa-globe"></i> <a href="http://orel-edu.ru" target="_blank" rel="nofollow noopener noreferrer">orel-edu.ru</a></li>
        </div>
        <p class="copy">© 2020 Цифровая образовательная среда Орловской области</p>
    </div>

</footer>
