
<header>
    <div class="header">
        <div class="logo_admin col" id="logo_admin"><i class="fas fa-user-cog fa-2x"></i>
            <form id ="auth" style="display: none;width: 30%;"  method="post">
                <div class="input-group" >
                    <span class="input-group-text">Логин: </span>
                    <input id="login" type="text" class="form-control" placeholder="Логин" aria-label="Логин" aria-describedby="addon-wrapping">
                </div>
                <div class="input-group" >
                    <span class="input-group-text">Пароль: </span>
                    <input id="password" type="password" class="form-control" id="inputPassword">
                </div>
                <div class="btn-group" role="group">
                    <input type="submit" value="Войти" /> </div>
            </form>
        </div>

        <div class="emblem" >
            <a href="/index.phtml">
                <img src="img/emblem.jpg" alt="герб Орловской области">
            </a>
        </div>
</header>