<?php
session_start();
$temp_main_link=$_SERVER['PHP_SELF'];
?>
<header>
    <div class="header">
    	<div class="logo_admin col" id="logo_admin">
            <?php
            if ($GLOBALS['auth']) {
                echo "Режим администратора " . $_SESSION['login'];
                ?>
                <a href=""><i id="logo_exit" class="fas fa-sign-out-alt fa-2x"></i></a>
                <?php
            } else {
                ?>

                <a href="/authorization.phtml"><i class="fas fa-user-cog fa-2x"></i></a>
                <?php
            }
            ?>
        </div>

        <div class="emblem" >
            <a href="<?=$temp_main_link?>">
                <img src="img/emblem.jpg" alt="герб Орловской области">
            </a>
        </div>
</header>