<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <title>Цифровая образовательная среда Орловской области</title>

</head>
<header>
<div class="row">
    <div class="logo_admin col"><i class="fas fa-user-cog fa-2x"></i></div>
    <div class="emblem col-11"><img src="img/emblem.jpg" alt="герб Орловской области" style="width: 10%;"></div>
</header>
<body>
<h2>Цифровая среда дополнительного образования Орловской области</h2>
<div class="map row">

</div>
<div class="content row">
    <div class="region">
        <h4>Районы Орловской области:</h4>
        <div class="list-group">
            <li class="list-group-item">An item</li>
            <li class="list-group-item">A second item</li>
            <li class="list-group-item">A third item</li>
            <li class="list-group-item">A fourth item</li>
            <li class="list-group-item">And a fifth one</li>
        </div>
    </div>
    <div class="district">
        <h4>Образовательные учреждения:</h4>
        <div class="list-group">
            <li class="list-group-item">An item <i class="fas fa-edit"></i> <i class="fas fa-times"></i></li>
            <li class="list-group-item">A second item <i class="fas fa-edit"></i> <i class="fas fa-times"></i></li>
            <li class="list-group-item">A third item <i class="fas fa-edit"></i> <i class="fas fa-times"></i></li>
            <li class="list-group-item">A fourth item <i class="fas fa-edit"></i> <i class="fas fa-times"></i></li>
        </div>
        <button type="button" class="btn btn-outline-secondary">Добавить образовательное учреждение</button>
    </div>
    <div class="school">
        <h4>Описание образовательного учреждения <i class="fas fa-edit"></i> <i class="fas fa-times"> </i></h4>
        <div class="btn-group" role="group">
            <button type="button" class="btn btn-outline-secondary">Отменить</button>
            <button type="button" class="btn btn-outline-secondary">Просмотр</button>
            <button type="button" class="btn btn-outline-secondary">Сохранить</button>
        </div>
        <div class="input-group">
        <span class="input-group-text">Район: </span>
        <input type="text" class="form-control" placeholder="Район" aria-label="Район" aria-describedby="addon-wrapping">
        </div>
        <div class="input-group">
        <span class="input-group-text">Учреждение дополнительного образования: </span>
        <input type="text" class="form-control" placeholder="Учреждение дополнительного образования" aria-label="Учреждение дополнительного образования" aria-describedby="addon-wrapping">
        </div>
        <div class="input-group">
        <span class="input-group-text">Полное название: </span>
        <input type="text" class="form-control" placeholder="Полное название" aria-label="Полное название" aria-describedby="addon-wrapping">
        </div>
        <div class="input-group">
        <span class="input-group-text">Полный адрес: </span>
        <input type="text" class="form-control" placeholder="Полный адрес" aria-label="Полный адрес" aria-describedby="addon-wrapping">
        </div>
        <div class="input-group">
        <span class="input-group-text">Руководитель/директор: </span>
        <input type="text" class="form-control" placeholder="Руководитель/директор" aria-label="Руководитель/директор" aria-describedby="addon-wrapping">
        </div>
        <div class="input-group">
        <span class="input-group-text">ФИО: </span>
        <input type="text" class="form-control" placeholder="ФИО" aria-label="ФИО" aria-describedby="addon-wrapping">
        </div>
        <div class="input-group">
        <span class="input-group-text">Телефон: </span>
        <input type="text" class="form-control" placeholder="Телефон" aria-label="Телефон" aria-describedby="addon-wrapping">
        </div>
        <div class="input-group">
        <span class="input-group-text">E-mail: </span>
        <input type="text" class="form-control" placeholder="E-mail" aria-label="E-mail" aria-describedby="addon-wrapping">
        </div>
        <div class="input-group">
        <span class="input-group-text">Ссылка на сайт: </span>
        <input type="text" class="form-control" placeholder="Ссылка на сайт" aria-label="РаСсылка на сайтйон" aria-describedby="addon-wrapping">
        </div>
        <div class="input-group">
        <span class="input-group-text">Дополнительная информация об учреждении</span>
        <textarea class="form-control" aria-label="Дополнительная информация об учреждении"></textarea>
        </div>
    </div>
</div>
</body>
<footer>
    <div class="container row">
        <div class="footer_contacts">
            <p class="title">Департамент образования Орловской области</p>
            <li class="adr"><i class="fas fa-map-marker-alt"></i> 302021, г. Орел, Ленина пл., д. 1.</li>
            <li class="mail"><i class="far fa-envelope"></i> E-mail: <a href="mailto:pr_obraz@adm.orel.ru">pr_obraz@adm.orel.ru</a></li>
            <li class="tel"><i class="fas fa-phone"></i> </i> <a href="tel:+74862598290">+7 (4862) 59-82-90</a></li>
            <li class="web"><i class="fas fa-globe"></i> <a href="http://orel-edu.ru" target="_blank" rel="nofollow noopener noreferrer">orel-edu.ru</a></li>
        </div>
        <p class="copy">© 2020 Цифровая образовательная среда Орловской области</p>
    </div>

</footer>
</html>