<?php
session_start();
include("auto.php");

if(!$_SESSION["is_auth"]){
    $GLOBALS['auth']=new AuthClass();
}

if (isset($_POST["login"]) && isset($_POST["password"])) { //Если логин и пароль были отправлены
    if (!$GLOBALS['auth']->auth($_POST["login"], $_POST["password"])) { //Если логин и пароль введен не правильно
        echo "<p style=\"color:red;\">Логин и пароль введен не правильно!</p>";
    }
}
$temp_main_link="/";

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
    content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
    integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script type="text/javascript" src="js/test.js"></script>
    <title>Цифровая образовательная среда Орловской области</title>

</head>

<?php include("header.phtml")?>
<body>

<h2 id="main">Цифровая среда дополнительного образования Орловской области</h2>
<div class="content row" >

            <div class="map-block col" >
                <div class="map" >
                    <?php include("map.phtml"); ?>
                </div>
            </div>

            <div class="right-block col">
                <?php include("content.phtml"); ?>
            </div>
</div>
</body>

<?php include("footer.phtml")?>



</html>
<script type="text/javascript" src="js/script.js"></script>
<script type="text/javascript">

    logo_exit.onclick = function(){
        var isAdmin = confirm("Вы точно хотите выйти?");
        if(isAdmin){
            <?php $GLOBALS['auth']->out();?>
        }
    }
</script>



