<?php
include("connect.php");
$link = mysqli_connect($host, $user, $password, $database)
or die("Ошибка " . mysqli_error($link));

$id_school = -500;
if($_POST['id_school']  != null){
    $id_school = $_POST['id_school'];
}

$full_name ="";
$name ="";
$id_district ="";
$point_y = "";
$point_x ="";
$img = "";
$adres =  "";
$director = "";
$director_name = "";
$phone = "";
$email = "";
$site = "";
$info = "";
$name_dist = "";
//$query ="SELECT * FROM school WHERE id_school =" . $id_school . ";" ;
$query ="SELECT `school`.*, `district`.`name` as `name_dist` FROM `school`, `district` WHERE `district`.`id_district` =`school`.`id_district` and id_school =" . $id_school ;

$result = mysqli_query($link, $query) or die("Ошибка " . mysqli_error($link));
if($result)
{
    while($row = $result->fetch_assoc())// получаем все строки в цикле по одной
    {
        $full_name = $row['full_name'];
        $name = $row['name'];
        $id_district = $row['id_district'];
        $point_y = $row['point_y'];
        $point_x = $row['point_x'];
        $img = $row['img'];
        $adres =  $row['adres'];
        $director = $row['director'];
        $director_name = $row['director_name'];
        $phone = $row['phone'];
        $email = $row['email'];
        $site = $row['site'];
        $info = $row['info'];
        $id_school = $row['id_school'];
        $name_dist = $row['name_dist'];

    }
}else {
    $full_name = "";
    $name = "";
    $id_district = "";
    $point_y = "";
    $point_x = "";
    $img = "";
    $adres = "";
    $director = "";
    $director_name = "";
    $phone = "";
    $email = "";
    $site = "";
    $info = "";
    $name_dist = "";
}
    $form_school = '<form action="db/db_insert_school.phtml" method="post">' .
        '<div class="card" style="width:100%">' .
        '<img src="' . $img . '" class="card-img-top" >' .
        '<div class="card-body">' .
        '<p class="text_school_info"><strong>Район: </strong></p>' .
        '<p class="text_school">'. $name_dist.'</p>'.
        '<p class="text_school_info"><strong>Учреждение дополнительного образования: </strong></p>' .
        '<p class="text_school">'.$name .'</p>'.
        '<p class="text_school_info"><strong>Полное название: </strong></p>' .
        '<p class="text_school">'.$full_name .'</p>'.
        '<p class="text_school_info"><strong>Полный адрес: </strong></p>' .
        '<p class="text_school">'.$adres.'</p>'.
        '<p class="text_school_info"><strong>Руководитель/директор: </strong></p>' .
        '<p class="text_school">'.$director .'</p>'.
        '<p class="text_school_info"><strong>ФИО: </strong></p>' .
        '<p class="text_school">'.$director_name.'</p>'.
        '<p class="text_school_info"><strong>Телефон: </strong></p>' .
        '<p class="text_school">'.$phone.'</p>'.
        '<p class="text_school_info"><strong>E-mail: </strong></p>' .
        '<p class="text_school">'.$email.'</p>'.
        '<p class="text_school_info"><strong>Ссылка на сайт: </strong></p>' .
        '<p class="text_school"><a href="'.$site.'">'.$site.'</a></p>'.
        '<p class="text_school_info"><strong>Дополнительная информация об учреждении: </strong></p>' .
        '<p class="text_school">'.$info.'</p>'.
        '</div>' .
        '</div>' .
        '</form>';

echo $form_school;

mysqli_close($link);
?>

