<?php
include("connect.php");
$link = mysqli_connect($host, $user, $password, $database)
or die("Ошибка " . mysqli_error($link));

$school_id = 'null';
$school_photo = $_POST['school_photo'];
$school_district = $_POST['school_district'];
$school_name = $_POST['school_name'];
$full_school_name = $_POST['full_school_name'];
$adress = $_POST['adress'];
$director = $_POST['director'];
$director_name = $_POST['director_name'];
$phone = $_POST['phone'];
$email = $_POST['email'];
$website = $_POST['website'];
$info = "Созвездие";
$point_x = 0;
$point_y = 0;
$id_district = 0;



$query ="INSERT INTO `school`".
"(`id_school`, `name`, `full_name`,".
" `adres`, `director`, `director_name`,".
" `phone`, `email`, `site`, `info`, `img`,".
" `point_x`, `point_y`, `id_district`) VALUES".
" (".$school_id.
",'".$school_name.
"','".$full_school_name.
"','".$adress.
"','".$director.
"','".$director_name.
"','".$phone.
"','".$email.
"','".$website.
"','".$info.
"','".$school_photo.
"',".$point_x.
",".$point_y.
",".$id_district.
");";

//echo $query;


$result = mysqli_query($link, $query) or die("Ошибка " . mysqli_error($link));
if($result)
{
    //echo "<span style='color:blue;'>Данные добавлены</span>";
}

mysqli_close($link);

header ('Location: /');
?>



