<?php
include("connect.php");
$link = mysqli_connect($host, $user, $password, $database)
or die("Ошибка " . mysqli_error($link));

$query ="SELECT id_district,name FROM district";
$result = mysqli_query($link, $query) or die("Ошибка " . mysqli_error($link));

$array_values = array();


//
if($result)
{
    while($row = $result->fetch_assoc())// получаем все строки в цикле по одной
    {
        //создание массива с индексами и названиями регионов
        $array_values[] = $row;
    }
}
echo json_encode($array_values);
mysqli_close($link);
?>